"""FastAPI REST API routes for BLACKBOX: AI Agent Flight Recorder."""
from datetime import datetime, timezone
import json
import math
from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from backend.database import get_db
from backend.models import (
    Checkpoint,
    DiagnosisResult,
    EvaluationBenchmark,
    ReplayResult,
    Run,
    Step,
)
from backend.diagnosis.hybrid import HybridDiagnosisEngine
from backend.diagnosis.historical import KNOWN_FAILURE_PATTERNS
from backend.replay import ReplayEngine
from backend.evaluation import BenchmarkRunner

router = APIRouter(prefix="/api", tags=["BLACKBOX API"])
engine = HybridDiagnosisEngine()


class ReplayRequest(BaseModel):
    step_id: str
    modified_input: Dict[str, Any] = Field(default_factory=dict)


@router.get("/health")
def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "app": "BLACKBOX",
        "subtitle": "AI Agent Flight Recorder",
        "version": "2.1.0",
        "offline_mode": True,
        "disclaimer": "Synthetic demo data generated by deterministic code.",
    }


@router.get("/runs")
def list_runs(
    status: Optional[str] = None,
    agent_name: Optional[str] = None,
    db: Session = Depends(get_db),
):
    """List all recorded agent flight runs."""
    query = db.query(Run)
    if status:
        query = query.filter(Run.status == status.upper())
    if agent_name:
        query = query.filter(Run.agent_name.ilike(f"%{agent_name}%"))

    runs = query.order_by(Run.started_at.desc()).all()
    results = []
    for r in runs:
        r_dict = r.to_dict()
        diag = db.query(DiagnosisResult).filter(DiagnosisResult.run_id == r.id).first()
        r_dict["diagnosis_summary"] = {
            "suspect_step_id": diag.suspect_step_id if diag else None,
            "suspect_step_name": diag.suspect_step_name if diag else None,
            "suspicion_score": round(diag.suspicion_score, 1) if diag else 0.0,
            "confidence_label": diag.confidence_label if diag else "NORMAL",
        } if diag else None
        results.append(r_dict)

    return {"runs": results, "total": len(results)}


@router.get("/runs/{run_id}")
def get_run(run_id: str, db: Session = Depends(get_db)):
    """Retrieve full details of a specific flight run including steps and diagnosis."""
    run = db.query(Run).filter(Run.id == run_id).first()
    if not run:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found.")

    steps = db.query(Step).filter(Step.run_id == run_id).order_by(Step.step_index).all()
    diag = db.query(DiagnosisResult).filter(DiagnosisResult.run_id == run_id).first()
    checkpoints = db.query(Checkpoint).filter(Checkpoint.run_id == run_id).order_by(Checkpoint.step_index).all()

    run_dict = run.to_dict()
    run_dict["steps"] = [s.to_dict() for s in steps]
    run_dict["diagnosis"] = diag.to_dict() if diag else None
    run_dict["checkpoints"] = [c.to_dict() for c in checkpoints]

    return run_dict


@router.get("/runs/{run_id}/steps")
def get_run_steps(run_id: str, db: Session = Depends(get_db)):
    """Retrieve all ordered steps for a flight run."""
    steps = db.query(Step).filter(Step.run_id == run_id).order_by(Step.step_index).all()
    if not steps:
        raise HTTPException(status_code=404, detail=f"No steps found for run '{run_id}'.")
    return {"run_id": run_id, "steps": [s.to_dict() for s in steps]}


@router.get("/runs/{run_id}/graph")
def get_run_graph(run_id: str, db: Session = Depends(get_db)):
    """
    Generate non-linear Radial Graph nodes and edges formatted for React Flow.
    Center: Root Agent Node.
    Surrounding: Step nodes positioned in radial orbit with color-coded suspicion states.
    """
    run = db.query(Run).filter(Run.id == run_id).first()
    if not run:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found.")

    steps = db.query(Step).filter(Step.run_id == run_id).order_by(Step.step_index).all()
    diag = db.query(DiagnosisResult).filter(DiagnosisResult.run_id == run_id).first()
    suspect_step_id = diag.suspect_step_id if diag else None

    nodes = []
    edges = []

    # 1. Center Agent Root Node (positioned at 0, 0)
    center_x, center_y = 450, 320
    nodes.append({
        "id": "node_root_agent",
        "type": "agentRoot",
        "position": {"x": center_x, "y": center_y},
        "data": {
            "label": run.agent_name,
            "scenario": run.scenario,
            "status": run.status,
            "duration_ms": run.total_duration_ms,
            "isCenter": True,
        },
    })

    # 2. Orbiting Step Nodes in a Radial Ring
    num_steps = len(steps)
    radius = 260
    for idx, step in enumerate(steps):
        angle = (2 * math.pi * idx) / max(num_steps, 1) - (math.pi / 2)
        node_x = center_x + radius * math.cos(angle)
        node_y = center_y + radius * math.sin(angle)

        is_suspect = (step.id == suspect_step_id) or step.is_root_suspect
        is_downstream = step.is_downstream_impact or (step.status == "FAILED" and not is_suspect)

        node_type = "suspectNode" if is_suspect else "failureNode" if is_downstream else "stepNode"

        nodes.append({
            "id": step.id,
            "type": node_type,
            "position": {"x": round(node_x, 1), "y": round(node_y, 1)},
            "data": {
                "step_index": step.step_index,
                "step_name": step.step_name,
                "tool_name": step.tool_name,
                "status": step.status,
                "duration_ms": step.duration_ms,
                "suspicion_score": step.suspicion_score,
                "is_root_suspect": is_suspect,
                "is_downstream_impact": is_downstream,
                "side_effect_flag": step.side_effect_flag,
                "error_text": step.error_text,
            },
        })

        # Connect Agent Root to each Step node
        edges.append({
            "id": f"edge_root_{step.id}",
            "source": "node_root_agent",
            "target": step.id,
            "animated": is_suspect or is_downstream,
            "style": {
                "stroke": "#F59E0B" if is_suspect else "#EF4444" if is_downstream else "#CBD5E1",
                "strokeWidth": 2.5 if is_suspect else 1.5,
            },
        })

        # Connect sequential steps along orbit
        if idx > 0:
            prev_step = steps[idx - 1]
            edges.append({
                "id": f"edge_seq_{prev_step.id}_{step.id}",
                "source": prev_step.id,
                "target": step.id,
                "style": {"stroke": "#94A3B8", "strokeDasharray": "4 4"},
            })

    return {
        "run_id": run_id,
        "agent_name": run.agent_name,
        "nodes": nodes,
        "edges": edges,
        "summary": {
            "total_steps": num_steps,
            "suspect_node_id": suspect_step_id,
            "run_status": run.status,
        },
    }


@router.get("/runs/{run_id}/diagnosis")
def get_diagnosis(run_id: str, db: Session = Depends(get_db)):
    """Get hybrid diagnosis results for a flight run."""
    diag = db.query(DiagnosisResult).filter(DiagnosisResult.run_id == run_id).first()
    if not diag:
        # Compute on the fly if not cached
        return trigger_diagnosis(run_id, db)
    return diag.to_dict()


@router.post("/runs/{run_id}/diagnose")
def trigger_diagnosis(run_id: str, db: Session = Depends(get_db)):
    """Run full 5-signal Hybrid Diagnosis pipeline on a run."""
    run = db.query(Run).filter(Run.id == run_id).first()
    if not run:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found.")

    steps = db.query(Step).filter(Step.run_id == run_id).order_by(Step.step_index).all()
    step_dicts = [s.to_dict() for s in steps]

    diag_data = engine.diagnose_run(run.to_dict(), step_dicts)

    # Upsert DiagnosisResult
    diag_record = db.query(DiagnosisResult).filter(DiagnosisResult.run_id == run_id).first()
    if not diag_record:
        diag_record = DiagnosisResult(id=f"diag_{run_id}", run_id=run_id)
        db.add(diag_record)

    diag_record.suspect_step_id = diag_data["suspect_step_id"] or ""
    diag_record.suspect_step_name = diag_data["suspect_step_name"]
    diag_record.suspicion_score = diag_data["suspicion_score"]
    diag_record.rule_score = diag_data["top_signals"]["rule_match"]
    diag_record.anomaly_score = diag_data["top_signals"]["anomaly_signal"]
    diag_record.ranker_score = diag_data["top_signals"]["learned_ranker"]
    diag_record.dependency_score = diag_data["top_signals"]["dependency_impact"]
    diag_record.historical_score = diag_data["top_signals"]["historical_evidence"]
    diag_record.confidence_label = diag_data["confidence_label"]
    diag_record.explanation_text = diag_data["explanation_text"]
    diag_record.evidence_items_json = json.dumps(diag_data["top_evidence"])
    diag_record.breakdown_json = json.dumps(diag_data)
    diag_record.created_at = datetime.now(timezone.utc)

    # Update individual step suspicion scores
    step_map = {s["step_id"]: s["suspicion_score"] for s in diag_data.get("ranked_steps", [])}
    for s_obj in steps:
        if s_obj.id in step_map:
            s_obj.suspicion_score = step_map[s_obj.id]

    db.commit()
    return diag_record.to_dict()


@router.post("/runs/{run_id}/replay")
def replay_run(run_id: str, req: ReplayRequest, db: Session = Depends(get_db)):
    """
    Execute counterfactual replay from a checkpoint with intervention parameters
    and side-effect suppression.
    """
    run = db.query(Run).filter(Run.id == run_id).first()
    if not run:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found.")

    steps = db.query(Step).filter(Step.run_id == run_id).order_by(Step.step_index).all()
    step_dicts = [s.to_dict() for s in steps]

    replay_data = ReplayEngine.run_replay(
        run.to_dict(),
        step_dicts,
        req.step_id,
        req.modified_input,
    )

    # Save replay result
    rep_obj = ReplayResult(
        id=f"rep_{run_id}_{int(datetime.now(timezone.utc).timestamp())}",
        original_run_id=run_id,
        intervention_step_id=req.step_id,
        modified_input_json=json.dumps(req.modified_input),
        replay_status=replay_data["replay_status"],
        replayed_steps_json=json.dumps(replay_data["replayed_steps"]),
        suppressed_side_effects_json=json.dumps(replay_data["suppressed_side_effects"]),
        diff_summary_json=json.dumps(replay_data["diff_summary"]),
        experimental_evidence_notes=replay_data["experimental_evidence_notes"],
        created_at=datetime.now(timezone.utc),
    )
    db.add(rep_obj)
    db.commit()

    return rep_obj.to_dict()


@router.get("/runs/{run_id}/compare/{baseline_id}")
def compare_runs(run_id: str, baseline_id: str, db: Session = Depends(get_db)):
    """
    Compare a failed run against a baseline success run.
    Detects the first meaningful divergence point and state differences.
    """
    run_a = db.query(Run).filter(Run.id == run_id).first()
    run_b = db.query(Run).filter(Run.id == baseline_id).first()
    if not run_a or not run_b:
        raise HTTPException(status_code=404, detail="One or both runs not found for comparison.")

    steps_a = db.query(Step).filter(Step.run_id == run_id).order_by(Step.step_index).all()
    steps_b = db.query(Step).filter(Step.run_id == baseline_id).order_by(Step.step_index).all()

    min_len = min(len(steps_a), len(steps_b))
    divergence_step_index = None
    divergence_details = None

    comparison_steps = []
    for i in range(min_len):
        sa = steps_a[i].to_dict()
        sb = steps_b[i].to_dict()

        out_a = sa.get("output_data", {})
        out_b = sb.get("output_data", {})
        is_diff = (out_a != out_b) or (sa.get("status") != sb.get("status"))

        if is_diff and divergence_step_index is None:
            divergence_step_index = i
            divergence_details = {
                "step_index": i,
                "step_name": sa["step_name"],
                "tool_name": sa["tool_name"],
                "target_output": out_a,
                "baseline_output": out_b,
                "root_cause_diagnosis": (
                    "Arithmetic duplication in item breakdown causing budget overflow"
                    if "budget" in sa["tool_name"]
                    else "Output state deviation"
                ),
            }

        comparison_steps.append({
            "step_index": i,
            "step_name": sa["step_name"],
            "tool_name": sa["tool_name"],
            "target_run_status": sa["status"],
            "baseline_run_status": sb["status"],
            "is_divergent": is_diff,
            "target_duration_ms": sa["duration_ms"],
            "baseline_duration_ms": sb["duration_ms"],
        })

    return {
        "target_run_id": run_id,
        "baseline_run_id": baseline_id,
        "divergence_found": divergence_step_index is not None,
        "first_meaningful_divergence": divergence_details,
        "aligned_steps": comparison_steps,
    }


@router.get("/evaluation/benchmark")
def get_benchmark_report(db: Session = Depends(get_db)):
    """Retrieve latest evaluation benchmark results and accuracy metrics."""
    bench = db.query(EvaluationBenchmark).order_by(EvaluationBenchmark.evaluated_at.desc()).first()
    if not bench:
        data = BenchmarkRunner.run_benchmark()
        return data
    return bench.to_dict()


@router.post("/evaluation/run")
def run_benchmark_suite(db: Session = Depends(get_db)):
    """Re-execute the evaluation benchmark suite across all labeled test cases."""
    data = BenchmarkRunner.run_benchmark()
    bench = EvaluationBenchmark(
        id=f"bench_{int(datetime.now(timezone.utc).timestamp())}",
        benchmark_name=data["benchmark_name"],
        total_cases=data["total_cases"],
        top1_accuracy=data["models"]["blackbox_hybrid"]["top1_accuracy"],
        top3_accuracy=data["models"]["blackbox_hybrid"]["top3_accuracy"],
        mrr=data["models"]["blackbox_hybrid"]["mrr"],
        baselines_json=json.dumps(data["models"]),
        detailed_results_json=json.dumps(data["detailed_cases"]),
        evaluated_at=datetime.now(timezone.utc),
    )
    db.add(bench)
    db.commit()
    return bench.to_dict()


@router.get("/patterns")
def list_known_patterns():
    """Retrieve catalog of verified agent failure patterns and mitigation guidelines."""
    return {
        "patterns": KNOWN_FAILURE_PATTERNS,
        "total_patterns": len(KNOWN_FAILURE_PATTERNS),
        "disclaimer": "Synthetic pattern corpus for AI agent flight recorder diagnostics.",
    }
